name: position_fractal
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  path: ^1.8.3
  path_provider: ^2.0.15
  fractal_base:
    path: ../fractal_base
  fractal:
    path: ../fractal
  frac:
    path: ../frac
  signed_fractal:
    path: ../signed_fractal
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.4
  drift_dev: ^2.8.2
  lints: ^2.0.0
  test: ^1.21.0
